"""Curated initial catalog data for the canonical seed pipeline."""

from decimal import Decimal

from scripts.seed_types import (
    AliasSeed,
    CategorySeed,
    IngredientSeed,
    NutritionSeed,
    RecipeDetailsSeed,
    RecipeIngredientSeed,
    RecipeSeed,
    SeedDataset,
    ShelfLifeRuleSeed,
)
from src.model.enum_model import MeasurementUnit, ShelfLifeRuleScope, StorageMode

DEFAULT_DATASET = SeedDataset(
    categories=(
        CategorySeed(
            key="leafy-greens",
            name="Leafy greens",
            description="Fresh leafy vegetables.",
        ),
        CategorySeed(
            key="protein-foods",
            name="Protein foods",
            description="Fresh and frozen protein-rich foods.",
        ),
        CategorySeed(
            key="dry-goods",
            name="Dry goods",
            description="Shelf-stable pantry staples.",
        ),
        CategorySeed(
            key="fresh-produce",
            name="Fresh produce",
            description="Fresh fruit and vegetables stored at room temperature.",
        ),
    ),
    ingredients=(
        IngredientSeed(
            key="spinach",
            category_key="leafy-greens",
            name="Spinach",
            description="Fresh leafy spinach.",
            canonical_unit=MeasurementUnit.GRAM,
            default_storage_mode=StorageMode.REFRIGERATED,
            nutrition=NutritionSeed(
                calories=Decimal("23.000"),
                protein_g=Decimal("2.900"),
                fat_g=Decimal("0.400"),
                carbs_g=Decimal("3.600"),
                sugar_g=Decimal("0.400"),
                sodium_mg=Decimal("79.000"),
                other_nutrients={"fiber_g": 2.2},
            ),
        ),
        IngredientSeed(
            key="tofu",
            category_key="protein-foods",
            name="Tofu",
            description="Firm plain tofu.",
            canonical_unit=MeasurementUnit.GRAM,
            default_storage_mode=StorageMode.REFRIGERATED,
            nutrition=NutritionSeed(
                calories=Decimal("76.000"),
                protein_g=Decimal("8.100"),
                fat_g=Decimal("4.800"),
                carbs_g=Decimal("1.900"),
                sugar_g=Decimal("0.600"),
                sodium_mg=Decimal("7.000"),
                other_nutrients={"fiber_g": 0.3},
            ),
        ),
        IngredientSeed(
            key="chicken-breast",
            category_key="protein-foods",
            name="Chicken breast",
            description="Boneless skinless chicken breast.",
            canonical_unit=MeasurementUnit.GRAM,
            default_storage_mode=StorageMode.REFRIGERATED,
            nutrition=NutritionSeed(
                calories=Decimal("165.000"),
                protein_g=Decimal("31.000"),
                fat_g=Decimal("3.600"),
                carbs_g=Decimal("0.000"),
                sugar_g=Decimal("0.000"),
                sodium_mg=Decimal("74.000"),
                other_nutrients={"fiber_g": 0.0},
            ),
        ),
        IngredientSeed(
            key="rice",
            category_key="dry-goods",
            name="Rice",
            description="Uncooked white rice.",
            canonical_unit=MeasurementUnit.GRAM,
            default_storage_mode=StorageMode.DRY_SHELF,
            nutrition=NutritionSeed(
                calories=Decimal("365.000"),
                protein_g=Decimal("7.100"),
                fat_g=Decimal("0.700"),
                carbs_g=Decimal("80.000"),
                sugar_g=Decimal("0.100"),
                sodium_mg=Decimal("5.000"),
                other_nutrients={"fiber_g": 1.3},
            ),
        ),
        IngredientSeed(
            key="tomato",
            category_key="fresh-produce",
            name="Tomato",
            description="Fresh ripe tomato.",
            canonical_unit=MeasurementUnit.GRAM,
            default_storage_mode=StorageMode.ROOM_TEMPERATURE,
            nutrition=NutritionSeed(
                calories=Decimal("18.000"),
                protein_g=Decimal("0.900"),
                fat_g=Decimal("0.200"),
                carbs_g=Decimal("3.900"),
                sugar_g=Decimal("2.600"),
                sodium_mg=Decimal("5.000"),
                other_nutrients={"fiber_g": 1.2},
            ),
        ),
    ),
    aliases=(
        AliasSeed(
            normalized_alias="baby spinach",
            alias="Baby spinach",
            ingredient_key="spinach",
        ),
        AliasSeed(
            normalized_alias="firm tofu",
            alias="Firm tofu",
            ingredient_key="tofu",
        ),
        AliasSeed(
            normalized_alias="chicken fillet",
            alias="Chicken fillet",
            ingredient_key="chicken-breast",
        ),
        AliasSeed(
            normalized_alias="jasmine rice",
            alias="Jasmine rice",
            ingredient_key="rice",
        ),
        AliasSeed(
            normalized_alias="red tomato",
            alias="Red tomato",
            ingredient_key="tomato",
        ),
    ),
    shelf_life_rules=(
        ShelfLifeRuleSeed(
            scope=ShelfLifeRuleScope.CATEGORY,
            target_key="leafy-greens",
            storage_mode=StorageMode.REFRIGERATED,
            min_days=3,
            max_days=5,
            default_days=4,
        ),
        ShelfLifeRuleSeed(
            scope=ShelfLifeRuleScope.INGREDIENT,
            target_key="spinach",
            storage_mode=StorageMode.REFRIGERATED,
            min_days=2,
            max_days=4,
            default_days=3,
        ),
        ShelfLifeRuleSeed(
            scope=ShelfLifeRuleScope.CATEGORY,
            target_key="protein-foods",
            storage_mode=StorageMode.REFRIGERATED,
            min_days=2,
            max_days=3,
            default_days=2,
        ),
        ShelfLifeRuleSeed(
            scope=ShelfLifeRuleScope.CATEGORY,
            target_key="protein-foods",
            storage_mode=StorageMode.FROZEN,
            min_days=90,
            max_days=180,
            default_days=120,
        ),
        ShelfLifeRuleSeed(
            scope=ShelfLifeRuleScope.CATEGORY,
            target_key="dry-goods",
            storage_mode=StorageMode.DRY_SHELF,
            min_days=90,
            max_days=180,
            default_days=120,
        ),
        ShelfLifeRuleSeed(
            scope=ShelfLifeRuleScope.CATEGORY,
            target_key="fresh-produce",
            storage_mode=StorageMode.ROOM_TEMPERATURE,
            min_days=3,
            max_days=7,
            default_days=5,
        ),
    ),
    recipes=(
        RecipeSeed(
            key="spinach-soup",
            name="Spinach soup",
            details=RecipeDetailsSeed(
                description="A small bootstrap recipe using fresh spinach.",
                instructions={"steps": ["Wash spinach", "Cook for five minutes"]},
                default_servings=Decimal("2.00"),
                estimated_cooking_minutes=15,
                estimated_cost=25000.0,
                nutrition=NutritionSeed(
                    calories=Decimal("198.000"),
                    protein_g=Decimal("22.000"),
                    fat_g=Decimal("10.400"),
                    carbs_g=Decimal("11.000"),
                    sugar_g=Decimal("2.000"),
                    other_nutrients={"fiber_g": 5.0},
                ),
                tags={"values": ["quick", "vegetarian"]},
            ),
        ),
        RecipeSeed(
            key="chicken-rice-bowl",
            name="Chicken rice bowl",
            details=RecipeDetailsSeed(
                description="A protein-rich chicken, rice, and tomato bowl.",
                instructions={
                    "steps": [
                        "Cook rice",
                        "Cook chicken thoroughly",
                        "Serve with chopped tomato",
                    ]
                },
                default_servings=Decimal("2.00"),
                estimated_cooking_minutes=30,
                estimated_cost=45000.0,
                nutrition=NutritionSeed(
                    calories=Decimal("895.500"),
                    protein_g=Decimal("73.550"),
                    fat_g=Decimal("8.450"),
                    carbs_g=Decimal("123.900"),
                    sugar_g=Decimal("2.750"),
                    other_nutrients={"fiber_g": 3.15},
                ),
                tags={"values": ["high-protein", "meal-prep"]},
            ),
        ),
        RecipeSeed(
            key="tomato-spinach-tofu-stir-fry",
            name="Tomato spinach tofu stir-fry",
            details=RecipeDetailsSeed(
                description="A quick vegetarian stir-fry with fresh vegetables.",
                instructions={
                    "steps": [
                        "Cook tomato until soft",
                        "Add tofu and spinach",
                        "Stir-fry until heated through",
                    ]
                },
                default_servings=Decimal("2.00"),
                estimated_cooking_minutes=20,
                estimated_cost=35000.0,
                nutrition=NutritionSeed(
                    calories=Decimal("173.000"),
                    protein_g=Decimal("16.850"),
                    fat_g=Decimal("8.000"),
                    carbs_g=Decimal("14.250"),
                    sugar_g=Decimal("6.500"),
                    other_nutrients={"fiber_g": 5.05},
                ),
                tags={"values": ["quick", "vegetarian"]},
            ),
        ),
    ),
    recipe_ingredients=(
        RecipeIngredientSeed(
            recipe_key="spinach-soup",
            ingredient_key="spinach",
            required_quantity=Decimal("200.000"),
            unit=MeasurementUnit.GRAM,
        ),
        RecipeIngredientSeed(
            recipe_key="spinach-soup",
            ingredient_key="tofu",
            required_quantity=Decimal("200.000"),
            unit=MeasurementUnit.GRAM,
        ),
        RecipeIngredientSeed(
            recipe_key="chicken-rice-bowl",
            ingredient_key="chicken-breast",
            required_quantity=Decimal("200.000"),
            unit=MeasurementUnit.GRAM,
        ),
        RecipeIngredientSeed(
            recipe_key="chicken-rice-bowl",
            ingredient_key="rice",
            required_quantity=Decimal("0.150"),
            unit=MeasurementUnit.KG,
        ),
        RecipeIngredientSeed(
            recipe_key="chicken-rice-bowl",
            ingredient_key="tomato",
            required_quantity=Decimal("100.000"),
            unit=MeasurementUnit.GRAM,
        ),
        RecipeIngredientSeed(
            recipe_key="tomato-spinach-tofu-stir-fry",
            ingredient_key="tomato",
            required_quantity=Decimal("200.000"),
            unit=MeasurementUnit.GRAM,
        ),
        RecipeIngredientSeed(
            recipe_key="tomato-spinach-tofu-stir-fry",
            ingredient_key="spinach",
            required_quantity=Decimal("100.000"),
            unit=MeasurementUnit.GRAM,
        ),
        RecipeIngredientSeed(
            recipe_key="tomato-spinach-tofu-stir-fry",
            ingredient_key="tofu",
            required_quantity=Decimal("150.000"),
            unit=MeasurementUnit.GRAM,
        ),
    ),
)
