"""Unit tests for the Task 2.4 authentication service flows."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import cast
from uuid import UUID, uuid4

import pytest
from sqlalchemy.ext.asyncio import AsyncSession

from src.core.setting import JWT_ACCESS_SECRET, JWT_REFRESH_SECRET
from src.helper.pwd_hash import compare_hash, hashing
from src.model.auth_session_model import AuthSessionModel
from src.model.enum_model import AccountStatus, OTPChannel, OTPPurpose, UserRole
from src.model.user_model import UserModel
from src.module.auth.auth_dto import (
    LoginRequestDTO,
    PasswordOTPVerificationPurpose,
    RegisterRequestDTO,
    VerifyPasswordRequestDTO,
    VerifyRegisterRequestDTO,
)
from src.module.auth.auth_service import (
    AuthService,
    DuplicateRegistrationError,
    InvalidCredentialsError,
    SessionNotFoundError,
)
from src.service.jwt_service import JwtService
from src.service.otp_delivery_service import OTPDeliveryRequest
from src.service.otp_service import OTPInvalidCodeError, OTPService
from src.test.test_otp_service import FakeOTPStore


@dataclass
class FakeScalarResult:
    """Expose the scalar methods used by auth service queries."""

    value: object | None

    def scalar_one_or_none(self) -> object | None:
        """Return the configured one-or-none value."""
        return self.value

    def scalars(self) -> FakeScalarResult:
        """Return this result for collection conversion."""
        return self

    def all(self) -> list[AuthSessionModel]:
        """Return a configured session collection or an empty list."""
        if isinstance(self.value, list):
            return [item for item in self.value if isinstance(item, AuthSessionModel)]
        return []


@dataclass
class FakeDatabaseSession:
    """In-memory async-session subset for auth service tests."""

    query_values: list[object | None] = field(default_factory=list)
    added: list[object] = field(default_factory=list)
    commits: int = 0
    rollbacks: int = 0

    async def execute(self, _statement: object) -> FakeScalarResult:
        """Return queued query values in service-call order."""
        value = self.query_values.pop(0) if self.query_values else None
        return FakeScalarResult(value)

    def add(self, value: object) -> None:
        """Record a would-be persisted ORM model."""
        self.added.append(value)

    async def flush(self) -> None:
        """Assign IDs normally generated by SQLAlchemy insert defaults."""
        for value in self.added:
            if isinstance(value, AuthSessionModel) and value.id is None:
                value.id = uuid4()

    async def commit(self) -> None:
        """Record a successful transaction commit."""
        self.commits += 1

    async def rollback(self) -> None:
        """Record a database rollback."""
        self.rollbacks += 1


@dataclass
class FakeOTPDeliveryService:
    """Record outbound OTP messages without provider I/O."""

    requests: list[OTPDeliveryRequest] = field(default_factory=list)

    async def send_otp(self, request: OTPDeliveryRequest) -> str:
        """Record a provider request and return a non-sensitive reference."""
        self.requests.append(request)
        return "delivery-reference"


def _user(status: AccountStatus = AccountStatus.ACTIVE) -> UserModel:
    """Build a user fixture with a deterministic password."""
    return UserModel(
        id=UUID("018f0f90-26e6-7ce7-8f61-8769b9e5aabb"),
        name="Cloudian",
        phone_e164="+84901234567",
        password_hash=hashing("old-password"),
        role=UserRole.USER,
        status=status,
    )


def _service(
    database: FakeDatabaseSession,
    delivery: FakeOTPDeliveryService,
) -> AuthService:
    """Build the service using deterministic OTP/DB/delivery boundaries."""
    return AuthService(
        db_session=cast(AsyncSession, database),
        otp_service=OTPService(FakeOTPStore(), fixed_otp_code="123456"),
        otp_delivery_service=delivery,
    )


@pytest.mark.anyio
async def test_register_creates_unverified_user_and_sends_otp() -> None:
    """Registration persists only a temporary user before OTP verification."""
    database = FakeDatabaseSession(query_values=[None])
    delivery = FakeOTPDeliveryService()

    issued_otp = await _service(database, delivery).register(
        RegisterRequestDTO(phone="+84901234567", password="new-password"),
    )

    created_user = database.added[0]
    assert isinstance(created_user, UserModel)
    assert created_user.status is AccountStatus.UNVERIFIED
    assert compare_hash("new-password", created_user.password_hash)
    assert issued_otp.otp == delivery.requests[0].otp
    assert delivery.requests[0].template_id == "REGISTER"


@pytest.mark.anyio
async def test_register_rejects_a_duplicate_email_before_database_insert() -> None:
    """A second account cannot use an email already held by another account."""
    existing_user = _user()
    existing_user.email = "cloudian@example.com"
    database = FakeDatabaseSession(query_values=[None, existing_user])
    delivery = FakeOTPDeliveryService()

    with pytest.raises(DuplicateRegistrationError, match="Email is already registered"):
        await _service(database, delivery).register(
            RegisterRequestDTO(
                phone="+84907654321",
                password="new-password",
                email="cloudian@example.com",
            )
        )

    assert not database.added
    assert database.commits == 0


@pytest.mark.anyio
async def test_resend_register_otp_replaces_the_previous_code(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A newly issued registration OTP invalidates the previous Redis code."""
    generated_codes = iter(("654321", "987654"))

    def next_otp() -> str:
        return next(generated_codes)

    monkeypatch.setattr("src.service.otp_service.generate_otp", next_otp)
    user = _user(AccountStatus.UNVERIFIED)
    database = FakeDatabaseSession(query_values=[user])
    delivery = FakeOTPDeliveryService()
    store = FakeOTPStore()
    service = AuthService(
        db_session=cast(AsyncSession, database),
        otp_service=OTPService(store, fixed_otp_code="123456"),
        otp_delivery_service=delivery,
    )
    first_issue = await service.issue_and_send_otp(
        destination=user.phone_e164,
        purpose=OTPPurpose.REGISTER,
    )
    store.advance(60)

    second_issue = await service.resend_register_otp(user.phone_e164)

    assert second_issue.otp != first_issue.otp
    with pytest.raises(OTPInvalidCodeError):
        await service.otp_service.verify_otp(
            OTPChannel.SMS,
            user.phone_e164,
            OTPPurpose.REGISTER,
            first_issue.otp,
        )


@pytest.mark.anyio
async def test_verify_register_activates_user_without_creating_tokens() -> None:
    """A matching local OTP activates the user without opening a session."""
    user = _user(AccountStatus.UNVERIFIED)
    database = FakeDatabaseSession(query_values=[user])
    delivery = FakeOTPDeliveryService()
    service = _service(database, delivery)
    await service.issue_and_send_otp(
        "+84901234567",
        OTPPurpose.REGISTER,
    )

    await service.verify_register(
        VerifyRegisterRequestDTO(
            phone="+84901234567",
            otp="123456",
        ),
    )

    assert user.status is AccountStatus.ACTIVE
    assert user.phone_verified_at is not None
    assert not database.added


@pytest.mark.anyio
async def test_verify_change_password_revokes_existing_sessions() -> None:
    """Reset verification replaces the hash and runs the session-revoke update."""
    user = _user()
    database = FakeDatabaseSession(query_values=[user])
    delivery = FakeOTPDeliveryService()
    service = _service(database, delivery)
    await service.issue_and_send_otp(
        "+84901234567",
        OTPPurpose.RESET_PASSWORD,
    )

    await service.verify_change_password(
        VerifyPasswordRequestDTO(
            phone="+84901234567",
            otp="123456",
            purpose=PasswordOTPVerificationPurpose.RESET_PASSWORD,
            new_password="replacement-password",
        )
    )

    assert compare_hash("replacement-password", user.password_hash)
    assert database.commits == 1


@pytest.mark.anyio
async def test_login_and_refresh_use_purpose_specific_jwts() -> None:
    """Login creates both JWTs and refresh creates only a new access JWT."""
    user = _user()
    database = FakeDatabaseSession(query_values=[user])
    delivery = FakeOTPDeliveryService()
    service = _service(database, delivery)
    initial_pair = await service.login(
        LoginRequestDTO(phone="+84901234567", password="old-password"),
        "pytest",
    )
    created_session = database.added[0]
    assert isinstance(created_session, AuthSessionModel)
    access_payload = JwtService.verify_jwt(initial_pair.access_token, JWT_ACCESS_SECRET)
    refresh_payload = JwtService.verify_jwt(
        initial_pair.refresh_token,
        JWT_REFRESH_SECRET,
    )
    assert access_payload["purpose"] == "access"
    assert refresh_payload["purpose"] == "refresh"
    assert access_payload["sub"] == refresh_payload["sub"]
    assert access_payload["roles"] == refresh_payload["roles"]
    assert compare_hash(initial_pair.refresh_token, created_session.refresh_token_hash)
    database.query_values.extend([user, [created_session]])

    refreshed_access = await service.refresh_access_token(initial_pair.refresh_token)

    refreshed_payload = JwtService.verify_jwt(
        refreshed_access.access_token,
        JWT_ACCESS_SECRET,
    )
    assert refreshed_payload["purpose"] == "access"

    database.query_values.extend([user, []])
    with pytest.raises(SessionNotFoundError):
        await service.refresh_access_token(initial_pair.refresh_token)


@pytest.mark.anyio
async def test_logout_revokes_session_and_blocks_refresh_access() -> None:
    """Logout revokes the matching session so its refresh JWT cannot be reused."""
    user = _user()
    database = FakeDatabaseSession(query_values=[user])
    service = _service(database, FakeOTPDeliveryService())
    token_pair = await service.login(
        LoginRequestDTO(phone="+84901234567", password="old-password"),
        "pytest",
    )
    session = database.added[0]
    assert isinstance(session, AuthSessionModel)
    database.query_values.append([session])

    await service.logout(user.id, token_pair.refresh_token)

    assert session.revoked_at is not None
    database.query_values.extend([user, []])
    with pytest.raises(SessionNotFoundError):
        await service.refresh_access_token(token_pair.refresh_token)


@pytest.mark.anyio
async def test_login_uses_one_non_disclosing_error_for_bad_password() -> None:
    """Wrong passwords return the same safe authentication-domain failure."""
    user = _user()
    database = FakeDatabaseSession(query_values=[user])

    with pytest.raises(InvalidCredentialsError) as error:
        await _service(database, FakeOTPDeliveryService()).login(
            LoginRequestDTO(phone="+84901234567", password="wrong-password"),
            "pytest",
        )

    assert error.value.status_code == 401
    assert error.value.detail == "Invalid phone or password"
