"""initial digram

Revision ID: 446cf3ac3439
Revises: 
Create Date: 2026-08-31 14:42:44.144571
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '446cf3ac3439'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_categories',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recipes',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('instructions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('default_servings', sa.Float(), nullable=False),
    sa.Column('estimated_cooking_minutes', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('total_protein_g', sa.Float(), nullable=True),
    sa.Column('total_fat_g', sa.Float(), nullable=True),
    sa.Column('total_carbs_g', sa.Float(), nullable=True),
    sa.Column('total_sugar_g', sa.Float(), nullable=True),
    sa.Column('other_nutrients', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_e164', sa.String(), nullable=False),
    sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('UNVERIFIED', 'ACTIVE', 'BANNED', name='account_status'), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status <> 'ACTIVE' OR phone_verified_at IS NOT NULL", name='active_user_requires_verified_phone'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_e164')
    )
    op.create_table('auth_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(), nullable=False),
    sa.Column('token_family_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auth_sessions_token_family_id', 'auth_sessions', ['token_family_id'], unique=False)
    op.create_index('ix_auth_sessions_user_id_expires_at', 'auth_sessions', ['user_id', 'expires_at'], unique=False)
    op.create_table('device_registrations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fcm_token_hash', sa.String(), nullable=False),
    sa.Column('encrypted_fcm_token', sa.String(), nullable=False),
    sa.Column('platform', sa.Enum('ANDROID', 'IOS', 'WEB', name='device_platform'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fcm_token_hash')
    )
    op.create_table('favorite_menus',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_recipes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recipe_id')
    )
    op.create_table('master_ingredients',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('default_media_url', sa.String(), nullable=True),
    sa.Column('canonical_unit', sa.Enum('KG', 'GRAM', 'LITER', 'ML', 'PIECE', 'PACK', 'OTHER', name='measurement_unit'), nullable=False),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('sugar_g', sa.Float(), nullable=True),
    sa.Column('sodium_mg', sa.Float(), nullable=True),
    sa.Column('other_nutrients', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('default_storage_mode', sa.Enum('ROOM_TEMPERATURE', 'REFRIGERATED', 'FROZEN', 'DRY_SHELF', name='storage_mode'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['ingredient_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_plans',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('starts_on <= ends_on'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation_runs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('provider', sa.Enum('RULE_BASED_MVP', 'XGBOOST', 'LIGHTGBM', name='recommendation_provider_type'), nullable=False),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_notification_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('warning_days', sa.Integer(), nullable=True),
    sa.Column('expiring_soon_enabled', sa.Boolean(), nullable=False),
    sa.Column('expires_today_enabled', sa.Boolean(), nullable=False),
    sa.Column('expired_enabled', sa.Boolean(), nullable=False),
    sa.Column('leftover_reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('favorite_menu_items',
    sa.Column('favorite_menu_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_menu_id'], ['favorite_menus.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('favorite_menu_id', 'recipe_id')
    )
    op.create_table('ingredient_aliases',
    sa.Column('master_ingredient_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('normalized_alias', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['master_ingredient_id'], ['master_ingredients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_alias')
    )
    op.create_table('meal_plan_items',
    sa.Column('meal_plan_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_run_id', sa.UUID(), nullable=True),
    sa.Column('planned_for', sa.Date(), nullable=False),
    sa.Column('meal_slot', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', name='meal_slot'), nullable=False),
    sa.Column('servings', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'COMPLETED', 'SKIPPED', name='meal_plan_item_status'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('servings > 0'),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['recommendation_run_id'], ['recommendation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meal_plan_id', 'planned_for', 'meal_slot')
    )
    op.create_table('recipe_ingredients',
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('master_ingredient_id', sa.UUID(), nullable=False),
    sa.Column('required_quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.Enum('KG', 'GRAM', 'LITER', 'ML', 'PIECE', 'PACK', 'OTHER', name='measurement_unit'), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('preparation_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('required_quantity > 0'),
    sa.ForeignKeyConstraint(['master_ingredient_id'], ['master_ingredients.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation_items',
    sa.Column('recommendation_run_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('expiration_utilization_score', sa.Float(), nullable=False),
    sa.Column('availability_score', sa.Float(), nullable=False),
    sa.Column('preference_fit_score', sa.Float(), nullable=False),
    sa.Column('purchase_minimization_score', sa.Float(), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['recommendation_run_id'], ['recommendation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation_run_id', 'rank')
    )
    op.create_table('shelf_life_rules',
    sa.Column('scope', sa.Enum('INGREDIENT', 'CATEGORY', name='shelf_life_rule_scope'), nullable=False),
    sa.Column('master_ingredient_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('storage_mode', sa.Enum('ROOM_TEMPERATURE', 'REFRIGERATED', 'FROZEN', 'DRY_SHELF', name='storage_mode'), nullable=False),
    sa.Column('min_days', sa.Integer(), nullable=False),
    sa.Column('max_days', sa.Integer(), nullable=False),
    sa.Column('default_days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('(master_ingredient_id IS NULL) <> (category_id IS NULL)', name='shelf_life_rule_exactly_one_target'),
    sa.ForeignKeyConstraint(['category_id'], ['ingredient_categories.id'], ),
    sa.ForeignKeyConstraint(['master_ingredient_id'], ['master_ingredients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'storage_mode'),
    sa.UniqueConstraint('master_ingredient_id', 'storage_mode')
    )
    op.create_table('shopping_lists',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('meal_plan_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='shopping_list_status'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cooking_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('meal_plan_item_id', sa.UUID(), nullable=True),
    sa.Column('servings', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'COMPLETED', 'CANCELLED', name='cooking_session_status'), nullable=False),
    sa.Column('consumption_mode', sa.Enum('EXACT', 'HALF', 'USE_ALL_MATCHED', 'CUSTOM', name='cooking_consumption_mode'), nullable=True),
    sa.Column('nutrition_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('servings > 0'),
    sa.ForeignKeyConstraint(['meal_plan_item_id'], ['meal_plan_items.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopping_list_items',
    sa.Column('shopping_list_id', sa.UUID(), nullable=False),
    sa.Column('master_ingredient_id', sa.UUID(), nullable=True),
    sa.Column('custom_name', sa.String(), nullable=True),
    sa.Column('required_quantity', sa.Float(), nullable=False),
    sa.Column('available_quantity', sa.Float(), nullable=False),
    sa.Column('missing_quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.Enum('KG', 'GRAM', 'LITER', 'ML', 'PIECE', 'PACK', 'OTHER', name='measurement_unit'), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('(master_ingredient_id IS NULL) <> (custom_name IS NULL)', name='shopping_item_exactly_one_identity'),
    sa.CheckConstraint('available_quantity >= 0'),
    sa.CheckConstraint('missing_quantity >= 0'),
    sa.CheckConstraint('required_quantity > 0'),
    sa.ForeignKeyConstraint(['master_ingredient_id'], ['master_ingredients.id'], ),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_batches',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('master_ingredient_id', sa.UUID(), nullable=True),
    sa.Column('custom_name', sa.String(), nullable=True),
    sa.Column('batch_type', sa.Enum('RAW_INGREDIENT', 'COOKED_FOOD', name='inventory_batch_type'), nullable=False),
    sa.Column('initial_quantity', sa.Float(), nullable=False),
    sa.Column('current_quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.Enum('KG', 'GRAM', 'LITER', 'ML', 'PIECE', 'PACK', 'OTHER', name='measurement_unit'), nullable=False),
    sa.Column('storage_mode', sa.Enum('ROOM_TEMPERATURE', 'REFRIGERATED', 'FROZEN', 'DRY_SHELF', name='storage_mode'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DEPLETED', 'DISCARDED', 'ARCHIVED', name='inventory_batch_status'), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('packaged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiration_source', sa.Enum('MANUFACTURER', 'ESTIMATED', 'USER_OVERRIDE', 'UNKNOWN', name='expiration_source'), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'LEFTOVER', name='inventory_source'), nullable=False),
    sa.Column('source_cooking_session_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('(master_ingredient_id IS NULL) <> (custom_name IS NULL)', name='inventory_batch_exactly_one_identity'),
    sa.CheckConstraint('current_quantity >= 0'),
    sa.CheckConstraint('initial_quantity > 0'),
    sa.ForeignKeyConstraint(['master_ingredient_id'], ['master_ingredients.id'], ),
    sa.ForeignKeyConstraint(['source_cooking_session_id'], ['cooking_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cooking_consumptions',
    sa.Column('cooking_session_id', sa.UUID(), nullable=False),
    sa.Column('recipe_ingredient_id', sa.UUID(), nullable=True),
    sa.Column('inventory_batch_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.Enum('KG', 'GRAM', 'LITER', 'ML', 'PIECE', 'PACK', 'OTHER', name='measurement_unit'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('quantity > 0'),
    sa.ForeignKeyConstraint(['cooking_session_id'], ['cooking_sessions.id'], ),
    sa.ForeignKeyConstraint(['inventory_batch_id'], ['inventory_batches.id'], ),
    sa.ForeignKeyConstraint(['recipe_ingredient_id'], ['recipe_ingredients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_ledger_entries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('inventory_batch_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('INITIAL_STOCK', 'MANUAL_ADJUSTMENT', 'COOKING_CONSUMPTION', 'DISCARDED', 'LEFTOVER_CREATED', 'CORRECTION', name='inventory_ledger_event_type'), nullable=False),
    sa.Column('quantity_before', sa.Float(), nullable=False),
    sa.Column('quantity_delta', sa.Float(), nullable=False),
    sa.Column('quantity_after', sa.Float(), nullable=False),
    sa.Column('unit', sa.Enum('KG', 'GRAM', 'LITER', 'ML', 'PIECE', 'PACK', 'OTHER', name='measurement_unit'), nullable=False),
    sa.Column('cooking_session_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('quantity_after = quantity_before + quantity_delta'),
    sa.ForeignKeyConstraint(['cooking_session_id'], ['cooking_sessions.id'], ),
    sa.ForeignKeyConstraint(['inventory_batch_id'], ['inventory_batches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('inventory_batch_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('EXPIRING_SOON', 'EXPIRES_TODAY', 'EXPIRED', 'LEFTOVER_REMINDER', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('deduplication_key', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('UNREAD', 'READ', 'DISMISSED', name='notification_status'), nullable=False),
    sa.Column('delivery_status', sa.Enum('PENDING', 'SENT', 'RETRYING', 'FAILED', name='notification_delivery_status'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_batch_id'], ['inventory_batches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deduplication_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('inventory_ledger_entries')
    op.drop_table('cooking_consumptions')
    op.drop_table('inventory_batches')
    op.drop_table('shopping_list_items')
    op.drop_table('cooking_sessions')
    op.drop_table('shopping_lists')
    op.drop_table('shelf_life_rules')
    op.drop_table('recommendation_items')
    op.drop_table('recipe_ingredients')
    op.drop_table('meal_plan_items')
    op.drop_table('ingredient_aliases')
    op.drop_table('favorite_menu_items')
    op.drop_table('user_notification_preferences')
    op.drop_table('recommendation_runs')
    op.drop_table('meal_plans')
    op.drop_table('master_ingredients')
    op.drop_table('favorite_recipes')
    op.drop_table('favorite_menus')
    op.drop_table('device_registrations')
    op.drop_index('ix_auth_sessions_user_id_expires_at', table_name='auth_sessions')
    op.drop_index('ix_auth_sessions_token_family_id', table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_table('users')
    op.drop_table('recipes')
    op.drop_table('ingredient_categories')
    # ### end Alembic commands ###
