"""rm device label

Revision ID: d696b54796cb
Revises: 20260830_0003
Create Date: 2026-08-30 23:57:08.087699
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'd696b54796cb'
down_revision: str | Sequence[str] | None = '20260830_0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_auth_sessions_token_family_id', 'auth_sessions', ['token_family_id'], unique=False)
    op.create_index('ix_auth_sessions_user_id_expires_at', 'auth_sessions', ['user_id', 'expires_at'], unique=False)
    op.drop_column('auth_sessions', 'device_label')
    op.drop_constraint(op.f('cooking_consumptions_quantity_check'), 'cooking_consumptions', type_='check')
    op.drop_constraint(op.f('cooking_sessions_servings_check'), 'cooking_sessions', type_='check')
    op.drop_constraint(op.f('inventory_batches_current_quantity_check'), 'inventory_batches', type_='check')
    op.drop_constraint(op.f('inventory_batches_initial_quantity_check'), 'inventory_batches', type_='check')
    op.drop_constraint(op.f('inventory_ledger_entries_check'), 'inventory_ledger_entries', type_='check')
    op.drop_constraint(op.f('meal_plan_items_servings_check'), 'meal_plan_items', type_='check')
    op.drop_constraint(op.f('meal_plans_check'), 'meal_plans', type_='check')
    op.drop_constraint(op.f('recipe_ingredients_required_quantity_check'), 'recipe_ingredients', type_='check')
    op.drop_constraint(op.f('shopping_list_items_available_quantity_check'), 'shopping_list_items', type_='check')
    op.drop_constraint(op.f('shopping_list_items_missing_quantity_check'), 'shopping_list_items', type_='check')
    op.drop_constraint(op.f('shopping_list_items_required_quantity_check'), 'shopping_list_items', type_='check')
    op.create_check_constraint('active_user_requires_verified_phone', 'users', "status <> 'ACTIVE' OR phone_verified_at IS NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('active_user_requires_verified_phone', 'users', type_='check')
    op.create_check_constraint(op.f('shopping_list_items_required_quantity_check'), 'shopping_list_items', 'required_quantity > 0::double precision')
    op.create_check_constraint(op.f('shopping_list_items_missing_quantity_check'), 'shopping_list_items', 'missing_quantity >= 0::double precision')
    op.create_check_constraint(op.f('shopping_list_items_available_quantity_check'), 'shopping_list_items', 'available_quantity >= 0::double precision')
    op.create_check_constraint(op.f('recipe_ingredients_required_quantity_check'), 'recipe_ingredients', 'required_quantity > 0::double precision')
    op.create_check_constraint(op.f('meal_plans_check'), 'meal_plans', 'starts_on <= ends_on')
    op.create_check_constraint(op.f('meal_plan_items_servings_check'), 'meal_plan_items', 'servings > 0::double precision')
    op.create_check_constraint(op.f('inventory_ledger_entries_check'), 'inventory_ledger_entries', 'quantity_after = (quantity_before + quantity_delta)')
    op.create_check_constraint(op.f('inventory_batches_initial_quantity_check'), 'inventory_batches', 'initial_quantity > 0::double precision')
    op.create_check_constraint(op.f('inventory_batches_current_quantity_check'), 'inventory_batches', 'current_quantity >= 0::double precision')
    op.create_check_constraint(op.f('cooking_sessions_servings_check'), 'cooking_sessions', 'servings > 0::double precision')
    op.create_check_constraint(op.f('cooking_consumptions_quantity_check'), 'cooking_consumptions', 'quantity > 0::double precision')
    op.add_column('auth_sessions', sa.Column('device_label', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index('ix_auth_sessions_user_id_expires_at', table_name='auth_sessions')
    op.drop_index('ix_auth_sessions_token_family_id', table_name='auth_sessions')
    # ### end Alembic commands ###
